// Generated by `npm run database`. Do not edit.

import type { Indicator } from '../chemistry/indicators.ts';

/** Colour-transition ranges of the laboratory pH indicators. */
export const INDICATORS: Indicator[] = [
  {
    name: 'bromothymol blue',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'first transition (acid)',
        pH1: 0,
        pH2: 0,
        color1: '#ff0088',
        color2: '#ffff00',
      },
      {
        transition: 'second transition (base)',
        pH1: 6,
        pH2: 7.6,
        color1: '#ffff00',
        color2: '#0033ff',
      },
    ],
  },
  {
    name: 'cresol red',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'first transition (acid)',
        pH1: 0,
        pH2: 1,
        color1: '#ff0000',
        color2: '#ffff00',
      },
      {
        transition: 'second transition (base)',
        pH1: 7.2,
        pH2: 8.8,
        color1: '#ffff00',
        color2: '#ff0000',
      },
    ],
  },
  {
    name: 'gentian violet',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 0,
        pH2: 1.6,
        color1: '#ffff00',
        color2: '#b516e9',
      },
    ],
  },
  {
    name: 'malachite green',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'first transition (acid)',
        pH1: 0.2,
        pH2: 1.8,
        color1: '#ffff00',
        color2: '#00aaaa',
      },
      {
        transition: 'second transition (base)',
        pH1: 11.5,
        pH2: 13.2,
        color1: '#00aaaa',
        color2: '#ffffff',
      },
    ],
  },
  {
    name: 'thymol blue',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'first transition (acid)',
        pH1: 1.2,
        pH2: 2.8,
        color1: '#ff0000',
        color2: '#ffff00',
      },
      {
        transition: 'second transition (base)',
        pH1: 8,
        pH2: 9.6,
        color1: '#ffff00',
        color2: '#0000ff',
      },
    ],
  },
  {
    name: 'methyl yellow',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 2.9,
        pH2: 4,
        color1: '#ff0000',
        color2: '#ffff00',
      },
    ],
  },
  {
    name: 'bromophenol blue',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 3,
        pH2: 4.6,
        color1: '#ffff00',
        color2: '#ee82ee',
      },
    ],
  },
  {
    name: 'Congo red',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 3,
        pH2: 5.2,
        color1: '#0000ff',
        color2: '#ff0000',
      },
    ],
  },
  {
    name: 'methyl orange',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 3.1,
        pH2: 4.4,
        color1: '#ff0000',
        color2: '#ffff00',
      },
    ],
  },
  {
    name: 'screened methyl orange',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 3.2,
        pH2: 4.2,
        color1: '#ff00ff',
        color2: '#00ff00',
      },
    ],
  },
  {
    name: 'bromocresol green',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 3.8,
        pH2: 5.4,
        color1: '#ffff00',
        color2: '#0033ff',
      },
    ],
  },
  {
    name: 'methyl red',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 4.2,
        pH2: 6.3,
        color1: '#ff0000',
        color2: '#ffff00',
      },
    ],
  },
  {
    name: 'litmus',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 4.5,
        pH2: 8.3,
        color1: '#ff0000',
        color2: '#0000ff',
      },
    ],
  },
  {
    name: 'bromocresol purple',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 5.2,
        pH2: 6.8,
        color1: '#ffff00',
        color2: '#ee82ee',
      },
    ],
  },
  {
    name: 'phenol red',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 6.6,
        pH2: 8,
        color1: '#ffff00',
        color2: '#ff0000',
      },
    ],
  },
  {
    name: 'neutral red',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 6.8,
        pH2: 8,
        color1: '#ff0000',
        color2: '#ffcc00',
      },
    ],
  },
  {
    name: 'phenolphthalein',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 8.2,
        pH2: 10,
        color1: '#ffffff',
        color2: '#ffc0cb',
      },
    ],
  },
  {
    name: 'thymolphthalein',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 9.4,
        pH2: 10.6,
        color1: '#ffffff',
        color2: '#0000ff',
      },
    ],
  },
  {
    name: 'alizarin yellow R',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 10.1,
        pH2: 12,
        color1: '#ffff00',
        color2: '#ff3300',
      },
    ],
  },
  {
    name: 'alizarin',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 11,
        pH2: 12.4,
        color1: '#ff0000',
        color2: '#ee82ee',
      },
    ],
  },
  {
    name: 'indigo carmine',
    source:
      'https://docs.google.com/spreadsheets/d/1gTa_Sd4rdoZAs-G08PPf6LtM954vp_QHio9m0mYNamU',
    transitions: [
      {
        transition: 'single transition',
        pH1: 11.4,
        pH2: 13,
        color1: '#0000ff',
        color2: '#ffff00',
      },
    ],
  },
];
