/*
 * Regenerate `src/data/indicators.ts` from the vendored `ph-indicators.tsv`.
 *
 *   node data/update.ts
 *
 * The site is served as static files with a strict origin, so the table is
 * compiled into the bundle rather than fetched at runtime the way the
 * visualizer view it replaces used to.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { stdout } from 'node:process';

const dataDir = import.meta.dirname;
const outputFile = join(dataDir, '..', 'src', 'data', 'indicators.ts');

interface Transition {
  transition: string;
  pH1: number;
  pH2: number;
  color1: string;
  color2: string;
}

interface Indicator {
  name: string;
  source: string;
  transitions: Transition[];
}

const text = readFileSync(join(dataDir, 'ph-indicators.tsv'), 'utf8');
const [headerLine, ...rows] = text.trim().split('\n');
const header = (headerLine ?? '').split('\t');
const expected = [
  'transition',
  'name',
  'pH1',
  'pH2',
  'color1',
  'color2',
  'source',
];
if (header.join('\t') !== expected.join('\t')) {
  throw new Error(`unexpected header: ${header.join('\t')}`);
}

const byName = new Map<string, Indicator>();
for (const row of rows) {
  const cells = row.split('\t');
  const [transition, name, pH1, pH2, color1, color2, source] = cells;
  if (!name || !transition || !source) {
    throw new Error(`incomplete row: ${row}`);
  }
  for (const color of [color1, color2]) {
    if (!/^#[0-9a-f]{6}$/.test(color ?? '')) {
      throw new Error(`${name}: invalid colour ${color}`);
    }
  }
  const lower = Number(pH1);
  const upper = Number(pH2);
  if (!Number.isFinite(lower) || !Number.isFinite(upper)) {
    throw new Error(`${name}: invalid pH range`);
  }

  let indicator = byName.get(name);
  if (!indicator) {
    indicator = { name, source, transitions: [] };
    byName.set(name, indicator);
  }
  indicator.transitions.push({
    transition,
    pH1: lower,
    pH2: upper,
    color1: color1 as string,
    color2: color2 as string,
  });
}

const indicators = Array.from(byName.values()).toSorted(
  (a, b) => firstTransition(a) - firstTransition(b),
);

writeFileSync(
  outputFile,
  `// Generated by \`npm run database\`. Do not edit.

import type { Indicator } from '../chemistry/indicators.ts';

/** Colour-transition ranges of the laboratory pH indicators. */
export const INDICATORS: Indicator[] = ${JSON.stringify(indicators, null, 2)};
`,
  'utf8',
);
stdout.write(
  `wrote ${indicators.length} indicators (${rows.length} transitions)\n`,
);

function firstTransition(indicator: Indicator): number {
  return Math.min(...indicator.transitions.map((entry) => entry.pH1));
}
