name: Docker image

on:
  workflow_dispatch:
  push:
    tags:
      - 'equilibrium.cheminfo.org-v*'

jobs:
  docker:
    # Documentation: https://github.com/zakodium/workflows#docker-image
    uses: zakodium/workflows/.github/workflows/docker-image.yml@docker-image-v1
